### ISSUE TITLE
Nav Seed

### ISSUE THREAD

**Issue by TOI-Ingus** [dark-galaxy/dark-galaxy#10]
Just a placeholder to see if the planet images are generating randomly each time. 
![holder](https://user-images.githubusercontent.com/55919688/198848159-811c2e8e-4a48-4dfc-b5e3-4659503ae462.jpg)

**Comment by TOI-Ingus** [comment]
Current. 
![Screenshot_20221102-070757](https://user-images.githubusercontent.com/55919688/199422918-7628f31c-ce20-49d6-8e6a-84af61fc88dc.png)

**Comment by TOI-Ingus** [comment]
So looks like the nav seed might be bugged, first was from desktop and second from phone so shouldn't be a random cache issue

**Comment by Muffinman** [comment]
I'll check but it probably isn't random. I tried this with IC but it ends
up with 3 or 4 planets next to each other with the same image, in some
cases.

**Comment by TOI-Ingus** [comment]
Just closing this as discussed it seems to be an issue just how the speed game is setup and won't apply in live gameplay
