### ISSUE TITLE
Energy display

### ISSUE THREAD

**Issue by TOI-Ingus** [dark-galaxy/dark-galaxy#12]
When checking the hospital I noted something odd
![energy](https://user-images.githubusercontent.com/55919688/198848709-1b229368-ade2-4e44-b0b8-c3585742c65d.jpg)
![energy2](https://user-images.githubusercontent.com/55919688/198848710-c2d59d24-9d64-4249-b852-1f47960ac987.jpg)

It seems as though if you load energy it makes output go up. But it doesn't stop there as the energy the next turn is 200 more than it should be.

If you were crafty and noted this you might get a score boost just autoloading energy every turn.

**Comment by Muffinman** [comment]
Hopefully fixed, but will leave this open until we actually get to building hospitals.
