### ISSUE TITLE
DG not updating

### ISSUE THREAD

**Issue by Noropher** [dark-galaxy/dark-galaxy#2]
using chrome 
Versie 106.0.5249.103 (Officiële build) (64-bits)
Home connection Belgium, cabled (no issues for any other service, like streaming, downloading
seems it take longer to proces a request example, add some thing to build queue, than turn lenght

sometimes get this error 
Could not connect to the reCAPTCHA service. Please check your internet connection and reload to get a reCAPTCHA challenge.

must be an issue with chrome or an extension
installed a clean firefox and eveything is instant now

**Comment by Noropher** [comment]
![image](https://user-images.githubusercontent.com/115357986/194711069-91562b80-02de-4ce2-9cdd-0ee6bdf00943.png)

**Comment by Noropher** [comment]
I have enough
- pop
- air space
- resources
cant add Hyperspace , nothing happens, 2 turns later, its queued

**Comment by Muffinman** [comment]
Do you have any browser extensions etc. which could be blocking Google Recaptcha from loading?

Also, if possible, could you provide a screenshot of your Chrome inspector network tab? e.g.

![Screenshot 2022-10-08 at 15 14 38](https://user-images.githubusercontent.com/1319568/194711933-e2b43ba6-0cb2-44c9-ad2c-15e5b6af27d5.png)

1. Right click on page
2. Inspect Element
3. Click Network tab
4. F5 to reload page

**Comment by Noropher** [comment]
![image](https://user-images.githubusercontent.com/115357986/194712806-18fea447-60ba-410c-a9cc-f606c8bf131e.png)

**Comment by Noropher** [comment]
disabled all extensions for the dg page

**Comment by Muffinman** [comment]
Yeah looks like the top two requests there have been blocked or otherwise rewritten to a new URL. Glad you managed to sort it.
