### ISSUE TITLE
Possible Invasion Race Condition with 2 people hitting the button simultaniously

### ISSUE THREAD

**Issue by TOI-Ingus** [dark-galaxy/dark-galaxy#24]
This would also apply to colonising by since game reads in ms it seems unlikely that someone gets the exact same ms and so game must be registering based on the quickest response between the press and the db. Can't see this is something that can/should be stopped

**Comment by Muffinman** [comment]
Can't reasonably be fixed in current code, and very unlikely to happen in practice.
