### ISSUE TITLE
Completed structures appear as by magic

### ISSUE THREAD

**Issue by sunstello** [dark-galaxy/dark-galaxy#3]
Newly-colonized planet, after a few dozen turns, shows scads of useless buildings. Few workers.
![image](https://user-images.githubusercontent.com/40995629/194714458-7661470b-6478-4c6e-9f4a-5302cee4d3d9.png)

**Comment by Muffinman** [comment]
Known issue at the moment with some testing config left in by accident. Thanks for the report!
