### ISSUE TITLE
Register form username validation incorrect

### ISSUE THREAD

**Issue by arthurvanderwal81** [dark-galaxy/dark-galaxy#33]
Error message states: Username may only contain letters numbers, dashes and underscores

However username __420__ is not accepted

**Comment by Muffinman** [comment]
Just tested this and it would fail validation with `420` because it's not 4 characters long.

![Screenshot 2023-08-09 at 08 52 55](https://github.com/dark-galaxy/dark-galaxy/assets/1319568/9b500cb6-8023-46cf-9b34-8f19549c191e)
