### ISSUE TITLE
Different text sizes

### ISSUE THREAD

**Issue by TOI-Ingus** [dark-galaxy/dark-galaxy#6]
Just on radar tab, seems same on mobile and desktop witj chrome
![Screenshot_20221009-110421](https://user-images.githubusercontent.com/55919688/194751191-81f6c760-269b-4234-9813-f48a0686f2aa.png)

**Comment by Muffinman** [comment]
This seems to be happening less with the updated styles, but I'm going to give up on it as it mostly seems to be a Chrome bug.
